WIDGET_SPACE = 10
ACCOUNT_BUTTON_SIZE = (10, 2)
MESSAGE_FRAME_SIZE = (50, 10)
WINDOW_SIZE = (1280, 720)

LETTER_WIDTH = 16
LETTER_HEIGHT = 29

QUIT_EVENT = 'WM_DELETE_WINDOW'

INTERACTABLE_SIZE = 12
INTERACTABLE_NAME = "Comic Sans MS"
INTERACTABLE_FONT = (INTERACTABLE_NAME, INTERACTABLE_SIZE)
MESSAGE_SIZE = 8
MESSAGE_NAME = "Arial"
MESSAGE_FONT = (MESSAGE_NAME, MESSAGE_SIZE)

END = 'end'
WHITE = 'white'
CENTER = 'center'

COLORS = {'g': "#00FF00",
          'y': "#FFFF00",
          'p': "#FF00FF",
          'r': "#FF0000"}
