SOCKET_TIMEOUT = 0.1

WIDGET_SPACE = 10
ACCOUNT_BUTTON_SIZE = (10, 2)
MESSAGE_FRAME_SIZE = (50, 10)
WINDOW_SIZE = (1280, 720)
LOGO_SCALING_FACTOR = 3/4
LOBBY_COLUMNS = 8
PADX = 20
PADY = 5

N_PLAYERS = 8

LETTER_WIDTH = 16
LETTER_HEIGHT = 29

QUIT_EVENT = 'WM_DELETE_WINDOW'

INTERACTABLE_FONT = ("Comic Sans MS", 12)
MESSAGE_FONT = ("Arial", 8)
TITLE_FONT = ("Times New Roman", 36)

END = 'end'
WHITE = 'white'
CENTER = 'center'

COLORS = {'g': "#00FF00",
          'y': "#FFFF00",
          'p': "#FF00FF",
          'r': "#FF0000"}
